name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-api:
    #if: ${{ false }}
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
    - name: Restore packages
      run: nuget restore dotnet-core-tutorial
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build with MSBuild
      run: msbuild dotnet-core-tutorial\dotnet-core-tutorial.csproj -p:Configuration=Staging -p:DeployIisAppPath="Default Web Site" -p:OutputPath=\ -t:Package -p:PackageLocation=deploy.zip
    - uses: actions/upload-artifact@v3
      with:
        name: dotnet-core
        path: dotnet-core-tutorial\deploy.zip # or path/to/artifact
    - name: Deploy to EB
      uses: samplerepo
      with:
        aws_access_key: ${{ secrets.ACCESS_KEY }}
        aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
        application_name: test12
        environment_name: Test12-env
        version_label: ${{github.sha}}-env
        region: ap-south-1
        deployment_package: dotnet-core-tutorial\deploy.zip
